{"uid":"89af38f64dc9d3da","name":"An uncaught error was detected outside of a test","fullName":".An uncaught error was detected outside of a test","historyId":"52a12849550d3513996e41b83e83be38","time":{"start":1713878944163,"stop":1713878944321,"duration":158},"description":"","descriptionHtml":"","status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n                \n                  > Test argument \"title\" should be a string. Received type \"undefined\"\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n                \n                  > Test argument \"title\" should be a string. Received type \"undefined\"\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.\n                    at createInvalidArgumentTypeError (http://localhost:51820/__cypress/runner/cypress_runner.js:154932:13)\n                    at new Test (http://localhost:51820/__cypress/runner/cypress_runner.js:161003:11)\n                    at context.it.context.specify (http://localhost:51820/__cypress/runner/cypress_runner.js:160944:18)\n                    at createRunnable (http://localhost:51820/__cypress/runner/cypress_runner.js:145512:31)\n                    at <unknown> (http://localhost:51820/__cypress/runner/cypress_runner.js:145573:14)\n                    at Object.create (http://localhost:51820/__cypress/runner/cypress_runner.js:161180:19)\n                    at context.describe.context.context (http://localhost:51820/__cypress/runner/cypress_runner.js:160899:27)\n                    at createRunnable (http://localhost:51820/__cypress/runner/cypress_runner.js:145512:31)\n                    at <unknown> (http://localhost:51820/__cypress/runner/cypress_runner.js:145573:14)\n                    at <unknown> (http://localhost:51820/__cypress/runner/cypress_runner.js:110838:23)\n                    at tryCatcher (http://localhost:51820/__cypress/runner/cypress_runner.js:1807:23)\n                    at Object.gotValue (http://localhost:51820/__cypress/runner/cypress_runner.js:6476:18)\n                    at Object.gotAccum (http://localhost:51820/__cypress/runner/cypress_runner.js:6465:25)\n                    at Object.tryCatcher (http://localhost:51820/__cypress/runner/cypress_runner.js:1807:23)\n                    at Promise._settlePromiseFromHandler (http://localhost:51820/__cypress/runner/cypress_runner.js:1519:31)\n                    at Promise._settlePromise (http://localhost:51820/__cypress/runner/cypress_runner.js:1576:18)\n                    at Promise._settlePromise0 (http://localhost:51820/__cypress/runner/cypress_runner.js:1621:10)\n                    at Promise._settlePromises (http://localhost:51820/__cypress/runner/cypress_runner.js:1701:18)\n                    at _drainQueueStep (http://localhost:51820/__cypress/runner/cypress_runner.js:2407:12)\n                    at _drainQueue (http://localhost:51820/__cypress/runner/cypress_runner.js:2400:9)\n                    at Async._drainQueues (http://localhost:51820/__cypress/runner/cypress_runner.js:2416:5)\n                    at Async.drainQueues (http://localhost:51820/__cypress/runner/cypress_runner.js:2286:14)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"suite","value":""},{"name":"testClass","value":""},{"name":"testMethod","value":"An uncaught error was detected outside of a test"},{"name":"package","value":""},{"name":"resultFormat","value":"allure1"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"bd8fd979fd1c3fdf","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n                \n                  > selectWorkShift is not defined\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","time":{"start":1713878942403,"stop":1713878942629,"duration":226}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"89af38f64dc9d3da.json","parameterValues":[]}